bH5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tracks.urls')),
    path('admin/', admin.site.urls),
]

tracks/urls.py
from django.urls import path

from . import views

app_name = 'tracks'
urlpatterns = [
    path('', views.index, name='index'),
    path('track/<track_id>.gpx', views.get_gpx, name='get_gpx'),
    path('track/<track_id>.json', views.get_geojson, name='get_geojson'),
    path('track/<track_id>.svg', views.get_svg, name='get_svg'),
    path('track/<track_id>', views.detail, name='detail'),
    path('track', views.new_track, name='new_track'),
    path('user/<username>/', views.index_by_user, name='index_by_user'),
]

tracks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models as geomodels
from django.template.defaultfilters import pluralize
import uuid

class Track(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def display_name(self):
        if self.name:
            return self.name
        else:
            return self.id

    def segment_count(self):
        return self.segments.count()

    def point_count(self):
        return sum([segment.point_count() for segment in self.segments.all()])

    def __str__(self):
        return "Track({} | {} point{})".format(self.name if self.name else self.id, self.point_count(), pluralize(self.point_count()))

class Segment(models.Model):
    track = models.ForeignKey(Track, on_delete=models.CASCADE, related_name='segments')

    def point_count(self):
        return self.points.count()

    def __str__(self):
        return 'Segment({} | {} point{})'.format(self.id, self.point_count(), pluralize(self.point_count()))


class Point(models.Model):
    segment = models.ForeignKey(Segment, on_delete=models.CASCADE, related_name='points')
    latitude = models.DecimalField(max_digits=23, decimal_places=17)
    longitude = models.DecimalField(max_digits=23, decimal_places=17)
    point = geomodels.PointField()
    altitude = models.FloatField(null=True, blank=True)
    date = models.DateTimeField()

    def __str__(self):
        return 'Point({}|{}|{})'.format(self.id, self.latitude, self.longitude)

tracks/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Track
from .models import Segment
from .models import Point
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.views.decorators.http import require_http_methods

from django.contrib.gis.geos import Point as gisPoint

from django.db import transaction

import gpxpy
import gpxpy.gpx

import simplejson as json

def index(request):

    if 'lat' in request.GET.keys() and 'long' in request.GET.keys() and 'radius' in request.GET.keys():

        tracks = Track.objects.raw("""
        SELECT track.id
        FROM tracks_track as track
        INNER JOIN tracks_segment AS segment on segment.track_id = track.id
        INNER JOIN tracks_point AS point on point.segment_id = segment.id
        WHERE
            ST_DWithin(
                point.point::geography,
                'Point(%s %s)'::geography,
                %s)
        GROUP BY track.id;
        """, [float(request.GET['long']), float(request.GET['lat']), float(request.GET['radius'])])

        subset_name = 'search'

    else:
        tracks = Track.objects.order_by('-id')[:50]
        subset_name = 'latest 50 tracks'

    context = {
	'tracks': tracks,
        'loggedIn': request.user.is_authenticated,
        'subset_name': subset_name,
    }

    return render(request, 'tracks/index.html', context)


@transaction.atomic
@login_required(login_url='/admin')
@require_http_methods(["POST"])
def new_track(request):

    if not request.user.is_authenticated:
        raise PermissionDenied


    parsed_gpx = gpxpy.parse(request.POST['raw_gpx'])

    for track in parsed_gpx.tracks:

        new_track = Track(name=track.name, owner=request.user)
        new_track.save()

        for segment in track.segments:

            new_segment = Segment(track=new_track)
            new_segment.save()

            for point in segment.points:
                new_point = Point()
                new_point.latitude = point.latitude
                new_point.longitude = point.longitude
                new_point.altitude = point.elevation
                new_point.point = gisPoint(point.longitude, point.latitude, srid=4326)
                new_point.date = point.time
                new_point.segment = new_segment
                new_point.save()


    return HttpResponseRedirect(reverse('tracks:detail',args=(new_track.id,)))

def detail(request, track_id):

    tracks = Track.objects.all()

    if not request.user.is_authenticated:
        tracks = Track.objects.filter(public=True)

    track =  get_object_or_404(tracks, id=track_id)

    context = { 'track': track, 'segments': [] }

    segments = Segment.objects.filter(track=track)

    for segment in segments:
        context['segments'].append({
            'segment': segment,
            'points': Point.objects.filter(segment=segment).order_by('date'),
            'user': request.user,
        })

    return render(request, 'tracks/detail.html', context)

def get_gpx(request, track_id):

    tracks = Track.objects.all()

    if not request.user.is_authenticated:
        tracks = Track.objects.filter(public=True)

    track =  get_object_or_404(tracks, id=track_id)

    gpx = gpxpy.gpx.GPX()
    gpx_track = gpxpy.gpx.GPXTrack(name=track.name)
    gpx.tracks.append(gpx_track)

    segments = Segment.objects.filter(track=track)

    for segment in segments:

        gpx_segment = gpxpy.gpx.GPXTrackSegment()
        points = Point.objects.filter(segment=segment).order_by('date')

        for point in points:
            gpx_segment.points.append(gpxpy.gpx.GPXTrackPoint(
                point.latitude,
                point.longitude,
                elevation=point.altitude,
                time=point.date
            ))

        gpx_track.segments.append(gpx_segment)

    return HttpResponse(gpx.to_xml(), content_type="application/gpx+xml")
    #return HttpResponse(gpx.to_xml(), content_type="text/plain")

def get_svg(request, track_id):

    tracks = Track.objects.all()

    if not request.user.is_authenticated:
        tracks = Track.objects.filter(public=True)

    track =  get_object_or_404(tracks, id=track_id)

    results = Segment.objects.raw('''
        SELECT
            seg.id,
            ST_AsSVG(
                ST_Scale(
                    ST_Translate(
                        ST_MakeLine(p.point ORDER BY p.date),
                        min(st_x(p.point)) * (-1),
                        max(st_y(p.point)) * (-1)
                    )
                , 10000,10000),
            1, 4) as svg_line
        FROM tracks_segment as seg
        INNER JOIN tracks_point AS p
        ON seg.id = p.segment_id
        WHERE seg.track_id = %s
        GROUP BY seg.id;
            ''', [track.id], {'svg_line':'svg_line'});

    context = {
        'svg_path_data': [res.svg_line for res in results]
    }

    return render(request, 'tracks/track.svg', context, content_type="image/svg+xml")

def get_geojson(request, track_id):

    tracks = Track.objects.all()

    if not request.user.is_authenticated:
        tracks = Track.objects.filter(public=True)

    track =  get_object_or_404(tracks, id=track_id)

    geojson_object = {
        'type': 'FeatureCollection',
        'features': []
    }

    segments = Segment.objects.filter(track=track)



    for segment in segments:

        if segment.points.count() >= 2:

            geojson_segment = {
                'type': 'Feature',
                'properties': {},
                'geometry': {
                    'type': 'LineString',
                    'coordinates': []
                }
            }

            points = Point.objects.filter(segment=segment).order_by('date')

            for point in points:
                geojson_segment['geometry']['coordinates'].append([point.longitude, point.latitude])

            geojson_object['features'].append(geojson_segment)

    return HttpResponse(json.dumps(geojson_object), content_type="application/geo+json")


def index_by_user(request, username):

    tracks = Track.objects.all()

    if not request.user.is_authenticated:
        tracks = Track.objects.filter(public=True)

    context = {
        'tracks': get_list_or_404(tracks.filter(owner__username=username).order_by('-id')),
        'loggedIn': request.user.is_authenticated,
        'subset_name': 'tracks by ' + username,
    }

    return render(request, 'tracks/index.html', context)

tracks/templates/tracks/base.html
{% load static %}<!doctype html>
<html>
    <head>
        <meta chartset="utf-8">
        <title>bH5</title>

        <link rel="stylesheet" type="text/css" href="{% static 'tracks/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <meta http-equiv="x-ua-compatible" content="ie=edge">

    </head>

<body>

    <main>

        <header>
            <nav>
                <ul>
                    <li><a href="/">bH5</a></li>
                    <li><a href="/admin">admin</a></li>
                </ul>
            </nav>
        </header>

        <section>

            {% block content %}{% endblock %}

        </section>

        <footer>
            <p>proudly rendered by the server-side. ;)<p>
        </footer>

    </main>

</body>

</html>

tracks/templates/tracks/detail.html
{% extends 'tracks/base.html'%}

{% block content %}
    <h1>{{ track.display_name }}</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'admin:tracks_track_change' track.id %}">edit</a>
    {% endif %}
    <p>
        {{ track.point_count }} point{{ track.point_count|pluralize }}
        in {{ track.segment_count }} segment{{ track.segment_count|pluralize }}
        by user <a href="{% url 'tracks:index_by_user' user.username %}">{{ user.username }}</a>
        <br>permalink:
        <a href="{% url 'tracks:get_gpx' track.id %}">gpx</a>,
        <a href="{% url 'tracks:get_geojson' track.id %}">geojson</a>,
        <a href="{% url 'tracks:get_svg' track.id %}">svg</a>
    </p>




    {% if segments %}
        <img src="{% url 'tracks:get_svg' track.id %}" alt="svg path of the gps track" >

        <ul>
        {% for segment in segments %}
            <li>segment {{ forloop.counter }}</li>

            {% if segment.points %}
                <ul>
                {% for point in segment.points %}
                <li>{{ point.latitude }}, {{ point.longitude }}</li>
                {% endfor %}
                </ul>

            {% endif %}

        {% endfor %}
        </ul>
    {% else %}
        <p>empty track.</p>
    {% endif %}

{% endblock %}

tracks/templates/tracks/index.html
{% extends 'tracks/base.html'%}

{% block content %}

    <h1>{{ subset_name }}</h1>

    {% if tracks %}
        <ul class="track_list">
        {% for track in tracks %}
            <li>
                <a href="{% url 'tracks:detail' track.id %}">{{ track.display_name }}</a><br>
                permalink:
                <a href="{% url 'tracks:get_gpx' track.id %}">gpx</a>,
                <a href="{% url 'tracks:get_geojson' track.id %}">geojson</a>,
                <a href="{% url 'tracks:get_svg' track.id %}">svg</a>

            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>no tracks here.</p>
    {% endif %}

    {% if loggedIn %}

        <h1>new track</h1>
        <p>
            <form action="{% url 'tracks:new_track' %}" method="post">
            {% csrf_token %}
                <input type="text" placeholder="paste gpx here..." name="raw_gpx" />
                <input type="submit" value="insert">
            </form>
        <p>
    {% endif %}

{% endblock %}